city: Berlin
year: 2020
conference_dates: July 2020
venue_url: https://2020.ecoop.org/venue/ecoop-2020-venue
#past_editions:
#  - 2018
#  - 2017
#  - 2016
#  - 2015

# Possible states for cfp and registration: hidden, inactive,
# active and sold_out (for registration only). cfp_date
# and registration_date is displayed below the button if
# present and the state is set to inactive
cfp: inactive
cfp_date: Feb 20th
registration: inactive
registration_date: Opening soon

# Control different sections on the HP
show_talks: true
show_sponsors: true
show_organizers: true

# Footer contact details. Comment out to hide
footer_email: organizers@rebase-conf.org
footer_twitter: rebase-conf

featured_speakers:
- lars_bak

# Liquid can't create arrays
empty_array: []
